### ISSUE TITLE
Update Alias Operation

### ISSUE THREAD

**Issue by jyore** [openshift-mobile/openshift-mobile#35]
Should allow for an alias to be updated

**Comment by ron-murhammer** [comment]
Hey Joey. This is a pretty old issue that I noticed was assigned to me. I assume this still needs to be done? Did you want me to focus on this next?

**Comment by jyore** [comment]
Yeah, you were OOO last week when we went over everything.  Basically, you
can create and delete aliases, but you cannot modify one. This would be
adding that functionality.

Our goal is to have a minor release go up on the stores first of next
month.

**Comment by ron-murhammer** [comment]
Hey Andy/Joey,

What should you be able to update for aliases? It looks like when we create them we only send in name. You can't update the name of an alias and the only things you can update are ssl_certificate, private_key, and pass_phrase. I'm guessing since we don't allow people to enter this when they create one that we won't allow them to update them. I think this means update isn't useful for us. Here is the page describing it: https://access.redhat.com/site/documentation/en-US/OpenShift/2.0/html/REST_API_Guide/sect-API_Guide-Aliases_and_SSL_Certs-Update_Alias.html

Let me know what you think.

**Comment by jyore** [comment]
Makes sense
