### ISSUE TITLE
Create documentation for the Ripple Mobile Simulator

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#37]
Create documentation on the Ripple Mobile Simulator which covers the following concepts:
- Provide an introduction to Ripple
- Provide a step by step walkthrough of the installation, configuration and usage of Ripple for the OpenShift Mobile project

**Comment by ron-murhammer** [comment]
Added basic Ripple setup to the Getting Started page: https://github.com/sabre1041/openshift-mobile/wiki/Getting-Started.

Please look it over and let me know if you want me to add anything else.

**Comment by sabre1041** [comment]
Ripple documentation looks good. Would you be able to add the various environment variables used by the array of development tools. Feel free to reopen #36 as it pertains to that specific task

**Comment by ron-murhammer** [comment]
Added info around setting up environment variables and adding them to PATH for Java, Ant, and Android SDK: https://github.com/sabre1041/openshift-mobile/wiki/Getting-Started

**Comment by jyore** [comment]
Ran through the ripple setup last night and it worked for the most part. I had a small issue come up, I think because I had an old node install that wasn't compatible with the `connect` package. I was able to update npm and then it worked. I added a note to the docs.

Since it worked, I do not think there is anything else in the install and start section. Should we add info on how to use it or any specific features though?

**Comment by ron-murhammer** [comment]
It is pretty straightforward to use and not really any more difficult than using the Android emulator. Not really sure what else we would need to add. I think we can probably close this and always revisit it if other developers are having trouble setting it up or using it.

**Comment by sabre1041** [comment]
It may be beneficial to mention some of the limitations of Ripple compared with a full emulator such as issues relating to Same Origin Policy/Cross-Origin Resource Sharing

**Comment by ron-murhammer** [comment]
You actually can make cross domain requests using the ripple setting 'Cross Domain Proxy'. Ripple actually uses its server to proxy the requests made by the app so that the browser doesn't block them. In general, I think really the only drawback is that Ripple doesn't support 100% of the operations and you should always eventually test on actual Android/iOS/Windows devices. Here is the best article I found covering features/settings/etc: http://codingsquare.blogspot.com/2014/01/using-ripple-to-emulate-apache-cordova.html

**Comment by ron-murhammer** [comment]
Added a basic Ripple overview to the getting started wiki page covering what I mentioned above: https://github.com/sabre1041/openshift-mobile/wiki/Getting-Started
