### ISSUE TITLE
Create production build workflow

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#41]
High level task for researching and implementing methods to build the OpenShift Mobile project to multiple mobile platforms. Small efforts of work will be created based on the following high level goals:
- Research available options for building PhoneGap applications
  - PhoneGap Build appears to be a viable option
- Document build  process

**Comment by ron-murhammer** [comment]
PhoneGap Build seems to work really well:
- Setup an initial account and connected build to github
- Application build link: https://build.phonegap.com/apps/796801/builds
- Added private key to sign build for Android
- Built release version for Android

**Comment by ron-murhammer** [comment]
General process strategies we need to discuss:
- Are there any pitfalls of using build.phonegap?
- Key signing: I created a initial private key to sign the app and uploaded it to build.phonegap as all apps must be signed to be submitted to any app store. Anyone that knows the password for the key can build the app from build.phonegap to create a release version. Does Red Hat already have keys that we should use? We need to make sure we decide on a key and stick with it since it is part of our app's identification.

**Comment by ron-murhammer** [comment]
Looked into automating build.phonegap to pull code and rebuild on any github push. It looks like we'll have to create a little web server to receive the github webhook and then call the build.phonegap API or use the one this guy created: http://autobuild.monkeh.me/

I also sent you all an invite to the build.phonegap project

**Comment by ron-murhammer** [comment]
I also tried doing a webhook directly to build.phonegap but it doesn't work. I added this to webhooks on my fork to test it: https://build.phonegap.com/apps/796801/push?auth_token=a3JCxprDtWiXpEx37Psn

It sends a POST request to that URL instead of a GET so it fails with a '404'
