### ISSUE TITLE
Back button closes app when not supposed to

### ISSUE THREAD

**Issue by jyore** [openshift-mobile/openshift-mobile#62]
To reproduce:
Login -> Domains -> Select Domain to Applications -> Select Application -> use nav menu to go to Domains -> press back button

**Comment by jyore** [comment]
Check that. Anytime it is on domain page it exits. 

Is this acceptable or should it return to prev page? The application page always returns to prev page (domain or specific app). if applist does this then domain should. If domain always exits then applist should always go to domain

**Comment by sabre1041** [comment]
There is a check to enforce back button functionality to prevent going back to the login page after authenticating. Since the domains page is hit after logging in, the initial implementation was to exit the app rather than going back to the app to emulate what would occur on login page. Additional checks should be done to verify previous page. If login page, exit app. Otherwise proceed with back navigation

**Comment by jyore** [comment]
Ok, I will take the issue. Also adding tags and adding to BETA milestone
