### ISSUE TITLE
Create Demo App for Red Hat Summit

### ISSUE THREAD

**Issue by sabre1041** [openshift-mobile/openshift-mobile#75]
The OpenShift Mobile Application will be featured during the Red Hat Summit presentation [The Red Hat Cloud guide to all things xPaaS](http://www.redhat.com/summit/sessions/index.html#439). During this session, an demonstration of the OpenShift Mobile application will be covered. Accompanying this presentation should include a demonstration of creating an application from an existing git source code repository.

The project included should include the following
- A simple OpenShift cartridge application (php/python/perl to provide a quick launch of the application)
- Application should provide some sort of theme related to Red Hat Summit
- Database persistence
  - Demonstrate an embedded cartridge (such as mysql/mongodb/postgresql)

Validate the application can be created successfully and the steps required to ensure successful demonstration during the session

**Comment by jyore** [comment]
Possible idea for 'what the app does' is an email list to 'register they attended session' or 'send more info' or something along those lines. If exploring the 'send more info' route, could have options for 'using', 'contributing', etc

Then we have a really simple CRUD app that could be somewhat useful.

Thoughts??

**Comment by sabre1041** [comment]
How about a feedback application?

Allows the user to enter basic contact information (name, email).

Provide them with a textbox where they would be able to enter comments and then a checkbox whether they should be registered to receive further notifications on the application

**Comment by jyore** [comment]
Could do that yeah.

**Comment by ghost** [comment]
Could we also add a set of radio buttons to determine the OpenShift[Mobile] use/interest?

**Comment by jyore** [comment]
can you elaborate?

**Comment by ghost** [comment]
something like 'Do you currently use Openshift?'
No, it doesn't interest me; No, but I would like to; Yes, Openshift Origin; Yes, Openshift Online; Yes, Openshift Enterprise

And a check box asking if they are a user and/or administrator

It kind of helps us get an idea of the audience we had at Summit so we can figure out where the majority of interest in this is

**Comment by jyore** [comment]
I have the project created at: https://github.com/OpenShiftMobile/openshift-mobile-app-demo
I stood it up using the mobile app (Python 2.6 & MySQL 5.5) and can be accessed at: http://summitdemo-osmdemo.rhcloud.com/

It should be generic enough that we can reuse it for any type of questionnaire. The data is put in from the questionnaire management commands and inserted by passing an argument to manage.py dataload <loadout>. The web page is dynamically created from Questionnaire being loaded and the answers are automatically handled as well.  Each form must contain an email field, however.

root context will bring up the last added questionnaire or a specific one can be grabbed from /questionnaire/<questionnaire-id>

The only thing that remains is setting up auto-email on submission.  This is easy to do, however, the server credentials would be stored in plain-text in the repo. Because of this, we need to figure out how to get the server credentials inside the server without storing it in the app repo.

**Comment by sabre1041** [comment]
App created and demonstrated at Summit
